name: Python Linting/Testing

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests discord.py mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup database
      run: |
        sudo /etc/init.d/mysql start
        mysql -h 127.0.0.1 -uroot -p"${{ secrets.DB_PASSWORD }}" < /home/runner/work/Aiess/Aiess/test_schema.sql
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        OSU_API_KEY: ${{ secrets.OSU_API_KEY }}
        ROOT_PATH: /home/runner/work/Aiess/Aiess
      run: |
        pytest
